name: Docker Wol Alpine Arm64

on:
  workflow_dispatch:

jobs:
  build-wol:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.0.0
        with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
 
      - name: Build the Wol Docker image Arm64
        run: docker buildx build --platform=linux/arm64 --file alpine/3.16/wol/0.2.1/Dockerfile --tag ghcr.io/${{ github.actor }}/wol:0.2.1-alpine-arm64 . --load

      - name: Push the Wol Docker image Arm64
        run: docker push ghcr.io/${{ github.actor }}/wol:0.2.1-alpine-arm64
